Refactor/categories spec
ifmeorg/ifme pull request #1867
Opened 2020-10-03 10:05 UTC by andrewhchang

# Description
Refactor Categories controller spec to a request spec

## Corresponding Issue
closes #1822

2020-10-03 10:11 UTC, andrewhchang commented
I'm wondering if there's any way to make git diff the two files? :\

2020-10-03 16:01 UTC, julianguyen commented
Did you delete the file and then create a new one? I think if you do `git mv [old file] [new one]` you end up with a diff.

2020-10-03 16:08 UTC, julianguyen submitted a review, later dismissed
Solid work! Thanks for taking this on 🎊

2020-10-03 18:06 UTC, bennpham approved these changes
This looks fine to me at the moment. 👍 

I'm reading through this comment http://rspec.info/blog/2016/07/rspec-3-5-has-been-released/#comment-3868711294 in regards to Rspec recommendation for request spec over controller specs and I'm wondering to myself whether `render_template` matcher is part of the `rails-controller-testing` gem or not. If it is, then we'd probably want to switch that to `expect(response).to be_successful` instead. If its still fine, I think it should do. Ideally, I think once all of the controller specs are converted to request specs, we should be able to remove the `rails-controller-testing` gem.

I got to head off for a bit so I haven't check it myself to see yet, but I might take a look once I'm back on my computer.

2020-10-03 23:20 UTC, bennpham requested changes
Let's change all these `render_template` to `be_successful`. I just checked by removing `rails-controller-testing` gem and request spec don't support `render_template` by default.

It is [recommended to avoid the gem](http://rspec.info/blog/2016/07/rspec-3-5-has-been-released/#comment-3869319771) so if you assert that going to this URL is successful, that should be sufficient 👍

2020-10-03 23:20 UTC, bennpham commented on spec/requests/categories_spec.rb
> +        expect(response).to render_template('index')
```suggestion
        expect(response).to be_successful
```

2020-10-03 23:20 UTC, bennpham commented on spec/requests/categories_spec.rb
> +          expect(response).to render_template('show')
```suggestion
          expect(response).to be_successful
```

2020-10-03 23:20 UTC, bennpham commented on spec/requests/categories_spec.rb
> +        expect(response).to render_template('new')
```suggestion
        expect(response).to be_successful
```

2020-10-03 23:20 UTC, bennpham commented on spec/requests/categories_spec.rb
> +          expect(response).to render_template('edit')
```suggestion
          expect(response).to be_successful
```

2020-10-03 23:20 UTC, bennpham commented on spec/requests/categories_spec.rb
> +          expect(response).to render_template('new')
```suggestion
          expect(response).to be_successful
```

2020-10-03 23:20 UTC, bennpham commented on spec/requests/categories_spec.rb
> +          expect(response).to render_template('edit')
```suggestion
          expect(response).to be_successful
```

2020-10-04 00:54 UTC, andrewhchang commented
> Did you delete the file and then create a new one? I think if you do `git mv [old file] [new one]` you end up with a diff.

yeah I did, I'll use git mv` and see if i can merge the two files so that I keep the commits

2020-10-04 00:54 UTC, andrewhchang commented
> Let's change all these `render_template` to `be_successful`. I just checked by removing `rails-controller-testing` gem and request spec don't support `render_template` by default.
> 
> It is [recommended to avoid the gem](http://rspec.info/blog/2016/07/rspec-3-5-has-been-released/#comment-3869319771) so if you assert that going to this URL is successful, that should be sufficient 👍

Sure thing! Happy to :)

2020-10-04 01:25 UTC, andrewhchang commented
not showing a diff :( but I preserved the old commits

2020-10-04 02:14 UTC, bennpham approved these changes
Looks good 👍

2020-10-04 02:18 UTC, julianguyen approved these changes
Great work! Feel free to merge!

2020-10-04 02:31 UTC, merged